=== patczar/ws_sierpniowe/waluty/waluty.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2021 rel. 3 (x64) (http://www.altova.com) by Patryk Czarnik (self-employed) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="ArrayOfExchangeRatesTable">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="ExchangeRatesTable" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="ExchangeRatesTable">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Table" type="xs:string"/>
				<xs:element name="No" type="xs:string"/>
				<xs:element name="EffectiveDate" type="xs:date"/>
				<xs:element name="Rates">
					<xs:complexType>
						<xs:sequence>
							<xs:element ref="Rate" minOccurs="0" maxOccurs="unbounded"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Rate">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Currency" type="xs:string"/>
				<xs:element name="Code" type="xs:string"/>
				<xs:element name="Mid" type="xs:decimal"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== patczar/ws_sierpniowe/waluty/tabela.xml
<?xml version="1.0" encoding="utf-8"?>
<ArrayOfExchangeRatesTable
  xmlns:xsd="http://www.w3.org/2001/XMLSchema"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="waluty.xsd">
	<ExchangeRatesTable>
		<Table>A</Table>
		<No>153/A/NBP/2021</No>
		<EffectiveDate>2021-08-10</EffectiveDate>
		<Rates>
			<Rate>
				<Currency>bat (Tajlandia)</Currency>
				<Code>THB</Code>
				<Mid>0.1163</Mid>
			</Rate>
			<Rate>
				<Currency>dolar amerykański</Currency>
				<Code>USD</Code>
				<Mid>3.8937</Mid>
			</Rate>
			<Rate>
				<Currency>dolar australijski</Currency>
				<Code>AUD</Code>
				<Mid>2.8568</Mid>
			</Rate>
			<Rate>
				<Currency>dolar Hongkongu</Currency>
				<Code>HKD</Code>
				<Mid>0.5003</Mid>
			</Rate>
			<Rate>
				<Currency>dolar kanadyjski</Currency>
				<Code>CAD</Code>
				<Mid>3.0974</Mid>
			</Rate>
			<Rate>
				<Currency>dolar nowozelandzki</Currency>
				<Code>NZD</Code>
				<Mid>2.7208</Mid>
			</Rate>
			<Rate>
				<Currency>dolar singapurski</Currency>
				<Code>SGD</Code>
				<Mid>2.8662</Mid>
			</Rate>
			<Rate>
				<Currency>euro</Currency>
				<Code>EUR</Code>
				<Mid>4.5681</Mid>
			</Rate>
			<Rate>
				<Currency>forint (Węgry)</Currency>
				<Code>HUF</Code>
				<Mid>0.012954</Mid>
			</Rate>
			<Rate>
				<Currency>frank szwajcarski</Currency>
				<Code>CHF</Code>
				<Mid>4.2272</Mid>
			</Rate>
			<Rate>
				<Currency>funt szterling</Currency>
				<Code>GBP</Code>
				<Mid>5.3977</Mid>
			</Rate>
			<Rate>
				<Currency>hrywna (Ukraina)</Currency>
				<Code>UAH</Code>
				<Mid>0.1456</Mid>
			</Rate>
			<Rate>
				<Currency>jen (Japonia)</Currency>
				<Code>JPY</Code>
				<Mid>0.03524</Mid>
			</Rate>
			<Rate>
				<Currency>korona czeska</Currency>
				<Code>CZK</Code>
				<Mid>0.1799</Mid>
			</Rate>
			<Rate>
				<Currency>korona duńska</Currency>
				<Code>DKK</Code>
				<Mid>0.6142</Mid>
			</Rate>
			<Rate>
				<Currency>korona islandzka</Currency>
				<Code>ISK</Code>
				<Mid>0.030866</Mid>
			</Rate>
			<Rate>
				<Currency>korona norweska</Currency>
				<Code>NOK</Code>
				<Mid>0.4358</Mid>
			</Rate>
			<Rate>
				<Currency>korona szwedzka</Currency>
				<Code>SEK</Code>
				<Mid>0.4471</Mid>
			</Rate>
			<Rate>
				<Currency>kuna (Chorwacja)</Currency>
				<Code>HRK</Code>
				<Mid>0.6090</Mid>
			</Rate>
			<Rate>
				<Currency>lej rumuński</Currency>
				<Code>RON</Code>
				<Mid>0.9292</Mid>
			</Rate>
			<Rate>
				<Currency>lew (Bułgaria)</Currency>
				<Code>BGN</Code>
				<Mid>2.3356</Mid>
			</Rate>
			<Rate>
				<Currency>lira turecka</Currency>
				<Code>TRY</Code>
				<Mid>0.4502</Mid>
			</Rate>
			<Rate>
				<Currency>nowy izraelski szekel</Currency>
				<Code>ILS</Code>
				<Mid>1.2075</Mid>
			</Rate>
			<Rate>
				<Currency>peso chilijskie</Currency>
				<Code>CLP</Code>
				<Mid>0.004956</Mid>
			</Rate>
			<Rate>
				<Currency>peso filipińskie</Currency>
				<Code>PHP</Code>
				<Mid>0.0772</Mid>
			</Rate>
			<Rate>
				<Currency>peso meksykańskie</Currency>
				<Code>MXN</Code>
				<Mid>0.1938</Mid>
			</Rate>
			<Rate>
				<Currency>rand (Republika Południowej Afryki)</Currency>
				<Code>ZAR</Code>
				<Mid>0.2628</Mid>
			</Rate>
			<Rate>
				<Currency>real (Brazylia)</Currency>
				<Code>BRL</Code>
				<Mid>0.7440</Mid>
			</Rate>
			<Rate>
				<Currency>ringgit (Malezja)</Currency>
				<Code>MYR</Code>
				<Mid>0.9208</Mid>
			</Rate>
			<Rate>
				<Currency>rubel rosyjski</Currency>
				<Code>RUB</Code>
				<Mid>0.0529</Mid>
			</Rate>
			<Rate>
				<Currency>rupia indonezyjska</Currency>
				<Code>IDR</Code>
				<Mid>0.00027073</Mid>
			</Rate>
			<Rate>
				<Currency>rupia indyjska</Currency>
				<Code>INR</Code>
				<Mid>0.052329</Mid>
			</Rate>
			<Rate>
				<Currency>won południowokoreański</Currency>
				<Code>KRW</Code>
				<Mid>0.003383</Mid>
			</Rate>
			<Rate>
				<Currency>yuan renminbi (Chiny)</Currency>
				<Code>CNY</Code>
				<Mid>0.6007</Mid>
			</Rate>
			<Rate>
				<Currency>SDR (MFW)</Currency>
				<Code>XDR</Code>
				<Mid>5.5211</Mid>
			</Rate>
		</Rates>
	</ExchangeRatesTable>
</ArrayOfExchangeRatesTable>
